# config.toml

env = "development"

grpc_port = "50051"

[postgres]
host = "postgres"
#host = "localhost"
port = 5432
user = "auction_user"
password = "auction_password"
dbname = "auction_db"
sslmode = "disable"
timeout = "4s"
idle_timeout = "60s"
max_pool_size = 10

[http_server]
address = "localhost:8080"
timeout = "4s"
idle_timeout = "60s"
port = "8080"