CREATE TABLE "user" (
                        "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        "name" text NOT NULL,
                        "email" varchar(64) NOT NULL,
                        "balance" int8,
                        PRIMARY KEY("id"),
                        UNIQUE ("email")
);

CREATE TABLE "lot" (
                       "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       "title" varchar(255) NOT NULL,
                       "start_price" int8 NOT NULL,
                       "step" int8 NOT NULL,
                       "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       "auction_id" int4,
                       "user_id" int4,
                       PRIMARY KEY("id")
);

CREATE TABLE "bid" (
                       "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       "price" int8 NOT NULL,
                       "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       "user_id" int4,
                       "lot_id" int4,
                       "auction_id" int4,
                       PRIMARY KEY("id")
);

CREATE TABLE "auction" (
                           "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           "closed_at" TIMESTAMPTZ,
                           "user_id" int4,
                           "winner_id" int4,
                           PRIMARY KEY("id")
);

INSERT INTO "user" ("id", "name", "email", "balance")
VALUES (1, 'Test User', 'test@example.com', 10000);

ALTER TABLE "lot" ADD CONSTRAINT "fk_lot_auction" FOREIGN KEY ("auction_id") REFERENCES "auction" ("id") ON DELETE CASCADE;
ALTER TABLE "lot" ADD CONSTRAINT "fk_lot_user" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

ALTER TABLE "bid" ADD CONSTRAINT "fk_bid_user" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;
ALTER TABLE "bid" ADD CONSTRAINT "fk_bid_lot" FOREIGN KEY ("lot_id") REFERENCES "lot" ("id") ON DELETE CASCADE;
ALTER TABLE "bid" ADD CONSTRAINT "fk_bid_auction" FOREIGN KEY ("auction_id") REFERENCES "auction" ("id") ON DELETE CASCADE;

ALTER TABLE "auction" ADD CONSTRAINT "fk_auction_user" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE SET NULL;
ALTER TABLE "auction" ADD CONSTRAINT "fk_auction_winner" FOREIGN KEY ("winner_id") REFERENCES "user" ("id") ON DELETE SET NULL;

CREATE INDEX idx_auctions_created_at ON auction (created_at);
CREATE INDEX idx_auctions_closed_at_winner_id ON auction (closed_at, winner_id);
CREATE INDEX idx_bids_auction_id ON bid (auction_id);
CREATE INDEX idx_bids_user_id ON bid (user_id);
CREATE INDEX idx_bids_auction_user ON bid (auction_id, user_id);

